-- Seed: all droids and all cycle requirements.
-- Safe to re-run (ON CONFLICT DO NOTHING).

INSERT INTO droid_tycoon_droids (name) VALUES
  ('2BB'),
  ('A-LT'),
  ('AMP WALKER'),
  ('ARG'),
  ('B-U4D'),
  ('B1 BATTLE'),
  ('B1 HEAVY'),
  ('B1 SECURITY'),
  ('B2 HEAVY'),
  ('B2 SUPER'),
  ('B2-RP'),
  ('BAL-CORE'),
  ('BB'),
  ('BB9'),
  ('BDX EXPLORER'),
  ('CB'),
  ('CYCLENS'),
  ('CYCLO-GRAV'),
  ('DRFT-R'),
  ('DRK-1 PROBE'),
  ('GONK'),
  ('GROUNDMECH'),
  ('GUNRUNNER'),
  ('HAUL-R'),
  ('HOV-R'),
  ('ID10'),
  ('IG'),
  ('KX'),
  ('LEP'),
  ('LNG-SHOT'),
  ('LO'),
  ('LOADLIFTER'),
  ('MECHA-DROID'),
  ('MO-TRAK'),
  ('MONO-WLKR'),
  ('MOUSE'),
  ('NAV-EX'),
  ('OPTI-POD'),
  ('OPTI-STRK'),
  ('ORB-WALKER'),
  ('PIT'),
  ('PROTO-ROLLER'),
  ('R2'),
  ('R3'),
  ('R4'),
  ('R5'),
  ('R6'),
  ('R7'),
  ('R8'),
  ('R9'),
  ('RIC'),
  ('RIC-1200'),
  ('ROLL-R'),
  ('SEN-TRI'),
  ('SENATE HOVERCAM'),
  ('SNOW MOUSE'),
  ('STRIKE-ORB'),
  ('TRAK-R'),
  ('TRI-TEK'),
  ('UTIL-TEC'),
  ('VECT-ARM')
ON CONFLICT (name) DO NOTHING;

-- Requirements: (cycle, step, droid_name, rarity)
-- Joined to droid_tycoon_droids by name at insert time.
INSERT INTO droid_tycoon_requirements (cycle, step, droid_id, rarity)
SELECT r.cycle, r.step, d.id, r.rarity
FROM (VALUES
  -- CYCLE 1
  (1,  1, 'PIT',              'base'),
  (1,  1, 'DRK-1 PROBE',      'base'),
  (1,  1, 'CB',               'base'),
  (1,  2, 'BAL-CORE',         'base'),
  (1,  2, 'BDX EXPLORER',     'base'),
  (1,  2, '2BB',              'base'),
  (1,  3, 'B-U4D',            'base'),
  (1,  3, 'A-LT',             'base'),
  (1,  3, 'R9',               'gold'),
  (1,  4, 'ARG',              'gold'),
  (1,  4, 'GROUNDMECH',       'base'),
  (1,  4, 'B1 SECURITY',      'gold'),
  (1,  5, 'B-U4D',            'gold'),
  (1,  5, 'HOV-R',            'gold'),
  (1,  5, 'R9',               'diamond'),
  (1,  6, 'ARG',              'diamond'),
  (1,  6, 'GROUNDMECH',       'gold'),
  (1,  6, 'A-LT',             'diamond'),
  (1,  7, 'B-U4D',            'diamond'),
  (1,  7, 'B1 SECURITY',      'diamond'),
  (1,  7, 'BB',               'gold'),
  (1,  8, 'LO',               'gold'),
  (1,  8, 'HOV-R',            'diamond'),
  (1,  8, 'UTIL-TEC',         'gold'),
  (1,  9, 'GROUNDMECH',       'rainbow'),
  (1,  9, 'TRAK-R',           'gold'),
  (1,  9, 'R6',               'gold'),
  (1, 10, 'LO',               'rainbow'),
  (1, 10, 'STRIKE-ORB',       'gold'),
  (1, 10, 'HAUL-R',           'rainbow'),
  (1, 11, 'AMP WALKER',       'rainbow'),
  (1, 11, 'B1 HEAVY',         'rainbow'),
  (1, 11, 'BB9',              'base'),
  (1, 12, 'MECHA-DROID',      'base'),
  (1, 12, 'MONO-WLKR',        'base'),
  (1, 12, 'PROTO-ROLLER',     'gold'),
  (1, 13, 'B2-RP',            'base'),
  (1, 13, 'CYCLO-GRAV',       'base'),
  (1, 13, 'R7',               'base'),
  (1, 14, 'MECHA-DROID',      'gold'),
  (1, 14, 'MONO-WLKR',        'gold'),
  (1, 14, 'OPTI-STRK',        'base'),
  (1, 15, 'B2-RP',            'gold'),
  (1, 15, 'R7',               'gold'),
  (1, 15, 'BB9',              'gold'),
  (1, 16, 'PROTO-ROLLER',     'diamond'),
  (1, 16, 'MONO-WLKR',        'diamond'),
  (1, 16, 'OPTI-STRK',        'gold'),
  (1, 17, 'MECHA-DROID',      'diamond'),
  (1, 17, 'B2-RP',            'diamond'),
  (1, 17, 'CYCLO-GRAV',       'diamond'),
  (1, 18, 'MONO-WLKR',        'rainbow'),
  (1, 18, 'R7',               'diamond'),
  (1, 18, 'BB9',              'diamond'),
  (1, 19, 'PROTO-ROLLER',     'rainbow'),
  (1, 19, 'B2-RP',            'rainbow'),
  (1, 19, 'CYCLO-GRAV',       'rainbow'),
  (1, 20, 'MECHA-DROID',      'rainbow'),
  (1, 20, 'OPTI-STRK',        'rainbow'),
  (1, 20, 'R7',               'rainbow'),
  (1, 21, 'GROUNDMECH',       'beskar'),
  (1, 21, 'ORB-WALKER',       'beskar'),
  (1, 21, 'BB',               'beskar'),
  (1, 22, 'AMP WALKER',       'beskar'),
  (1, 22, 'PROTO-ROLLER',     'beskar'),
  (1, 22, 'B1 HEAVY',         'beskar'),
  (1, 23, 'MONO-WLKR',        'beskar'),
  (1, 23, 'OPTI-STRK',        'beskar'),
  (1, 23, 'R7',               'beskar'),
  (1, 24, 'CYCLO-GRAV',       'beskar'),
  (1, 24, 'BB9',              'beskar'),
  (1, 24, 'MO-TRAK',          'base'),
  (1, 25, 'B2-RP',            'beskar'),
  (1, 25, 'IG',               'base'),
  (1, 25, 'DRFT-R',           'gold'),
  (1, 26, 'LOADLIFTER',       'diamond'),
  (1, 26, 'RIC-1200',         'rainbow'),
  (1, 26, 'CYCLENS',          'gold'),
  (1, 27, 'SNOW MOUSE',       'beskar'),
  (1, 27, 'KX',               'diamond'),
  (1, 27, 'TRI-TEK',          'rainbow'),
  -- CYCLE 2
  (2,  1, 'GONK',             'base'),
  (2,  1, 'MOUSE',            'base'),
  (2,  1, 'ID10',             'base'),
  (2,  2, 'SENATE HOVERCAM',  'base'),
  (2,  2, 'ROLL-R',           'base'),
  (2,  2, 'NAV-EX',           'base'),
  (2,  3, 'BDX EXPLORER',     'gold'),
  (2,  3, 'VECT-ARM',         'base'),
  (2,  3, 'R4',               'base'),
  (2,  4, 'BAL-CORE',         'gold'),
  (2,  4, '2BB',              'gold'),
  (2,  4, 'ORB-WALKER',       'base'),
  (2,  5, 'NAV-EX',           'gold'),
  (2,  5, 'VECT-ARM',         'gold'),
  (2,  5, 'R4',               'gold'),
  (2,  6, 'BAL-CORE',         'diamond'),
  (2,  6, 'GUNRUNNER',        'base'),
  (2,  6, '2BB',              'diamond'),
  (2,  7, 'BDX EXPLORER',     'diamond'),
  (2,  7, 'ROLL-R',           'diamond'),
  (2,  7, 'R2',               'gold'),
  (2,  8, 'GUNRUNNER',        'gold'),
  (2,  8, 'B2 SUPER',         'gold'),
  (2,  8, 'R4',               'diamond'),
  (2,  9, 'AMP WALKER',       'gold'),
  (2,  9, 'NAV-EX',           'rainbow'),
  (2,  9, 'STRIKE-ORB',       'gold'),
  (2, 10, 'VECT-ARM',         'rainbow'),
  (2, 10, 'B2 SUPER',         'diamond'),
  (2, 10, 'R2',               'diamond'),
  (2, 11, 'BAL-CORE',         'rainbow'),
  (2, 11, 'STRIKE-ORB',       'diamond'),
  (2, 11, 'B2 HEAVY',         'diamond'),
  (2, 12, 'R2',               'rainbow'),
  (2, 12, 'ORB-WALKER',       'rainbow'),
  (2, 12, 'BB9',              'base'),
  (2, 13, 'PROTO-ROLLER',     'base'),
  (2, 13, 'MECHA-DROID',      'base'),
  (2, 13, 'B2 SUPER',         'rainbow'),
  (2, 14, 'B2 HEAVY',         'rainbow'),
  (2, 14, 'B2-RP',            'base'),
  (2, 14, 'R7',               'gold'),
  (2, 15, 'PROTO-ROLLER',     'gold'),
  (2, 15, 'STRIKE-ORB',       'rainbow'),
  (2, 15, 'BB9',              'gold'),
  (2, 16, 'AMP WALKER',       'rainbow'),
  (2, 16, 'MECHA-DROID',      'gold'),
  (2, 16, 'B2-RP',            'diamond'),
  (2, 17, 'OPTI-POD',         'rainbow'),
  (2, 17, 'MONO-WLKR',        'gold'),
  (2, 17, 'R7',               'diamond'),
  (2, 18, 'PROTO-ROLLER',     'diamond'),
  (2, 18, 'UTIL-TEC',         'rainbow'),
  (2, 18, 'BB9',              'diamond'),
  (2, 19, 'MECHA-DROID',      'diamond'),
  (2, 19, 'B2-RP',            'rainbow'),
  (2, 19, 'R7',               'rainbow'),
  (2, 20, 'MONO-WLKR',        'rainbow'),
  (2, 20, 'OPTI-STRK',        'rainbow'),
  (2, 20, 'CYCLO-GRAV',       'rainbow'),
  (2, 21, 'LO',               'beskar'),
  (2, 21, 'HAUL-R',           'beskar'),
  (2, 21, 'R6',               'beskar'),
  (2, 22, 'SEN-TRI',          'beskar'),
  (2, 22, 'PROTO-ROLLER',     'beskar'),
  (2, 22, 'STRIKE-ORB',       'beskar'),
  (2, 23, 'B2-RP',            'beskar'),
  (2, 23, 'CYCLO-GRAV',       'beskar'),
  (2, 23, 'BB9',              'beskar'),
  (2, 24, 'SNOW MOUSE',       'base'),
  (2, 24, 'B2-RP',            'beskar'),
  (2, 24, 'OPTI-STRK',        'beskar'),
  (2, 25, 'MONO-WLKR',        'beskar'),
  (2, 25, 'RIC-1200',         'base'),
  (2, 25, 'TRI-TEK',          'gold'),
  (2, 26, 'KX',               'gold'),
  (2, 26, 'IG',               'rainbow'),
  (2, 26, 'DRFT-R',           'diamond'),
  (2, 27, 'LEP',              'diamond'),
  (2, 27, 'LOADLIFTER',       'rainbow'),
  (2, 27, 'MO-TRAK',          'beskar'),
  -- CYCLE 3
  (3,  1, 'PIT',              'base'),
  (3,  1, 'MOUSE',            'base'),
  (3,  1, 'GONK',             'base'),
  (3,  2, 'SENATE HOVERCAM',  'base'),
  (3,  2, 'R3',               'base'),
  (3,  2, '2BB',              'base'),
  (3,  3, 'R8',               'base'),
  (3,  3, 'R5',               'base'),
  (3,  3, 'R4',               'base'),
  (3,  4, 'B1 BATTLE',        'gold'),
  (3,  4, 'B1 SECURITY',      'gold'),
  (3,  4, 'R9',               'gold'),
  (3,  5, 'SENATE HOVERCAM',  'gold'),
  (3,  5, 'R3',               'gold'),
  (3,  5, '2BB',              'gold'),
  (3,  6, 'BDX EXPLORER',     'diamond'),
  (3,  6, 'R5',               'diamond'),
  (3,  6, 'R4',               'diamond'),
  (3,  7, 'B1 BATTLE',        'diamond'),
  (3,  7, 'R8',               'diamond'),
  (3,  7, 'R9',               'diamond'),
  (3,  8, 'B1 SECURITY',      'rainbow'),
  (3,  8, 'R3',               'rainbow'),
  (3,  8, '2BB',              'rainbow'),
  (3,  9, 'BDX EXPLORER',     'rainbow'),
  (3,  9, 'R5',               'rainbow'),
  (3,  9, 'R4',               'rainbow'),
  (3, 10, 'SENATE HOVERCAM',  'rainbow'),
  (3, 10, 'GROUNDMECH',       'base'),
  (3, 10, 'TRAK-R',           'base'),
  (3, 11, 'B2 HEAVY',         'base'),
  (3, 11, 'B2 SUPER',         'base'),
  (3, 11, 'UTIL-TEC',         'base'),
  (3, 12, 'BAL-CORE',         'rainbow'),
  (3, 12, 'GROUNDMECH',       'gold'),
  (3, 12, 'TRAK-R',           'gold'),
  (3, 13, 'PROTO-ROLLER',     'base'),
  (3, 13, 'MECHA-DROID',      'base'),
  (3, 13, 'B2 SUPER',         'rainbow'),
  (3, 14, 'B2 HEAVY',         'rainbow'),
  (3, 14, 'B2-RP',            'base'),
  (3, 14, 'R7',               'gold'),
  (3, 15, 'PROTO-ROLLER',     'gold'),
  (3, 15, 'STRIKE-ORB',       'rainbow'),
  (3, 15, 'BB9',              'gold'),
  (3, 16, 'AMP WALKER',       'rainbow'),
  (3, 16, 'MECHA-DROID',      'gold'),
  (3, 16, 'B2-RP',            'diamond'),
  (3, 17, 'OPTI-POD',         'rainbow'),
  (3, 17, 'MONO-WLKR',        'gold'),
  (3, 17, 'R7',               'diamond'),
  (3, 18, 'PROTO-ROLLER',     'diamond'),
  (3, 18, 'UTIL-TEC',         'rainbow'),
  (3, 18, 'BB9',              'diamond'),
  (3, 19, 'MECHA-DROID',      'diamond'),
  (3, 19, 'B2-RP',            'rainbow'),
  (3, 19, 'R7',               'rainbow'),
  (3, 20, 'MONO-WLKR',        'rainbow'),
  (3, 20, 'OPTI-STRK',        'rainbow'),
  (3, 20, 'CYCLO-GRAV',       'rainbow'),
  (3, 21, 'OPTI-POD',         'beskar'),
  (3, 21, 'B2 SUPER',         'beskar'),
  (3, 21, 'R2',               'beskar'),
  (3, 22, 'GUNRUNNER',        'beskar'),
  (3, 22, 'LNG-SHOT',         'beskar'),
  (3, 22, 'B2-RP',            'beskar'),
  (3, 23, 'MONO-WLKR',        'beskar'),
  (3, 23, 'MECHA-DROID',      'beskar'),
  (3, 23, 'CYCLO-GRAV',       'beskar'),
  (3, 24, 'RIC',              'base'),
  (3, 24, 'B2-RP',            'beskar'),
  (3, 24, 'BB9',              'beskar'),
  (3, 25, 'PROTO-ROLLER',     'beskar'),
  (3, 25, 'LOADLIFTER',       'base'),
  (3, 25, 'MO-TRAK',          'gold'),
  (3, 26, 'LEP',              'gold'),
  (3, 26, 'SNOW MOUSE',       'rainbow'),
  (3, 26, 'TRI-TEK',          'diamond'),
  (3, 27, 'RIC-1200',         'diamond'),
  (3, 27, 'IG',               'rainbow'),
  (3, 27, 'DRFT-R',           'beskar'),
  -- CYCLE 4
  (4,  1, 'PIT',              'base'),
  (4,  1, 'ID10',             'base'),
  (4,  1, 'DRK-1 PROBE',      'base'),
  (4,  2, 'SENATE HOVERCAM',  'base'),
  (4,  2, 'R3',               'base'),
  (4,  2, '2BB',              'base'),
  (4,  3, 'R8',               'gold'),
  (4,  3, 'R5',               'gold'),
  (4,  3, 'R4',               'base'),
  (4,  4, 'B1 BATTLE',        'gold'),
  (4,  4, 'B1 SECURITY',      'gold'),
  (4,  4, 'R9',               'gold'),
  (4,  5, 'SENATE HOVERCAM',  'gold'),
  (4,  5, 'R3',               'gold'),
  (4,  5, '2BB',              'gold'),
  (4,  6, 'BDX EXPLORER',     'diamond'),
  (4,  6, 'R5',               'diamond'),
  (4,  6, 'R4',               'diamond'),
  (4,  7, 'B1 BATTLE',        'diamond'),
  (4,  7, 'R8',               'diamond'),
  (4,  7, 'R9',               'diamond'),
  (4,  8, 'B1 SECURITY',      'rainbow'),
  (4,  8, 'R3',               'rainbow'),
  (4,  8, '2BB',              'rainbow'),
  (4,  9, 'BDX EXPLORER',     'rainbow'),
  (4,  9, 'R5',               'rainbow'),
  (4,  9, 'R4',               'rainbow'),
  (4, 10, 'SENATE HOVERCAM',  'rainbow'),
  (4, 10, 'GROUNDMECH',       'base'),
  (4, 10, 'TRAK-R',           'base'),
  (4, 11, 'B2 HEAVY',         'base'),
  (4, 11, 'B2 SUPER',         'base'),
  (4, 11, 'UTIL-TEC',         'base'),
  (4, 12, 'BAL-CORE',         'rainbow'),
  (4, 12, 'GROUNDMECH',       'gold'),
  (4, 12, 'TRAK-R',           'gold'),
  (4, 13, 'PROTO-ROLLER',     'base'),
  (4, 13, 'MECHA-DROID',      'base'),
  (4, 13, 'B2 SUPER',         'rainbow'),
  (4, 14, 'BAL-CORE',         'diamond'),
  (4, 14, 'GROUNDMECH',       'diamond'),
  (4, 14, 'TRAK-R',           'rainbow'),
  (4, 15, 'B2 HEAVY',         'diamond'),
  (4, 15, 'B2 SUPER',         'rainbow'),
  (4, 15, 'B2-RP',            'base'),
  (4, 16, 'UTIL-TEC',         'rainbow'),
  (4, 16, 'BB9',              'base'),
  (4, 16, 'R7',               'gold'),
  (4, 17, 'MECHA-DROID',      'gold'),
  (4, 17, 'OPTI-STRK',        'base'),
  (4, 17, 'CYCLO-GRAV',       'gold'),
  (4, 18, 'B2-RP',            'gold'),
  (4, 18, 'BB9',              'gold'),
  (4, 18, 'R7',               'diamond'),
  (4, 19, 'MECHA-DROID',      'diamond'),
  (4, 19, 'B2-RP',            'rainbow'),
  (4, 19, 'R7',               'rainbow'),
  (4, 20, 'MONO-WLKR',        'rainbow'),
  (4, 20, 'OPTI-STRK',        'rainbow'),
  (4, 20, 'CYCLO-GRAV',       'rainbow'),
  (4, 21, 'AMP WALKER',       'beskar'),
  (4, 21, 'GROUNDMECH',       'beskar'),
  (4, 21, 'HAUL-R',           'beskar'),
  (4, 22, 'GUNRUNNER',        'beskar'),
  (4, 22, 'STRIKE-ORB',       'beskar'),
  (4, 22, 'B2 SUPER',         'beskar'),
  (4, 23, 'MONO-WLKR',        'beskar'),
  (4, 23, 'B2-RP',            'beskar'),
  (4, 23, 'CYCLO-GRAV',       'beskar'),
  (4, 24, 'PROTO-ROLLER',     'beskar'),
  (4, 24, 'MECHA-DROID',      'beskar'),
  (4, 24, 'MO-TRAK',          'base'),
  (4, 25, 'OPTI-STRK',        'beskar'),
  (4, 25, 'TRI-TEK',          'base'),
  (4, 25, 'DRFT-R',           'gold'),
  (4, 26, 'LEP',              'diamond'),
  (4, 26, 'CYCLENS',          'gold'),
  (4, 26, 'MO-TRAK',          'rainbow'),
  (4, 27, 'RIC-1200',         'diamond'),
  (4, 27, 'SNOW MOUSE',       'rainbow'),
  (4, 27, 'LOADLIFTER',       'beskar')
) AS r(cycle, step, droid_name, rarity)
JOIN droid_tycoon_droids d ON d.name = r.droid_name
ON CONFLICT DO NOTHING;
